### PR TITLE
CMSIS DSP Demonstration Example

### PR DESCRIPTION
**Pull request by ioannis-karachalios**
This sample code demonstrates using the CMSIS DSP library. In this context, few test vectors provided by CMSIS are executed.

### CODE REVIEW

**Comment by ioannis-karachalios** [comment]
@koen-vdm can you please elaborate on the CI report? It's not clear to me why the CI fails to find the project.

**Comment by koen-vdm** [comment]
hello @ioannis-karachalios, 
Please see [my other comment](https://github.com/dialog-semiconductor/BLE_SDK10_DA1459x_examples/pull/4#issuecomment-2202030512), this is a similar issue.

**Review by Aart-Kleinendorst — APPROVED** [review]
Tested the sw example and readme.md looks ok.

**Comment by Aart-Kleinendorst** [comment]
Merging the DSP-lib example into main and deleted the branch.

**Pull request merged**
